### ISSUE TITLE
npm run build:linux throws error

### ISSUE THREAD

**Issue by KentShikama** [MaKleSoft/padlock#102]
```
$ npm run build:linux

> padlock@2.0.0-beta.1 build:linux /home/kent/Documents/padlock
> gulp build --linux --silent

electron-builder 19.19.1
No native production dependencies
Packaging for linux x64 using electron 1.7.5 to dist/linux-unpacked
Unhandled rejection Error: Exit code: ENOENT. spawn icns2png ENOENT
    at /home/kent/Documents/padlock/node_modules/electron-builder-util/src/util.ts:67:16
    at exithandler (child_process.js:277:5)
    at ChildProcess.errorhandler (child_process.js:289:5)
    at emitOne (events.js:115:13)
    at ChildProcess.emit (events.js:210:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
    at exec (/home/kent/Documents/padlock/node_modules/electron-builder-util/src/util.ts:45:3)
    at /home/kent/Documents/padlock/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:162:28
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at LinuxTargetHelper.createFromIcns (/home/kent/Documents/padlock/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:205:11)
    at /home/kent/Documents/padlock/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:54:25
From previous event:
    at LinuxTargetHelper.computeDesktopIcons (/home/kent/Documents/padlock/node_modules/electron-builder/out/targets/LinuxTargetHelper.js:84:11)
    at new LinuxTargetHelper (/home/kent/Documents/padlock/node_modules/electron-builder/src/targets/LinuxTargetHelper.ts:17:23)
    at getHelper (/home/kent/Documents/padlock/node_modules/electron-builder/src/linuxPackager.ts:33:18)
    at outDir (/home/kent/Documents/padlock/node_modules/electron-builder/src/linuxPackager.ts:62:122)
    at mapper (/home/kent/Documents/padlock/node_modules/electron-builder/src/targets/targetFactory.ts:50:16)
    at LinuxPackager.createTargets (/home/kent/Documents/padlock/node_modules/electron-builder/src/linuxPackager.ts:62:7)
    at createTargets (/home/kent/Documents/padlock/node_modules/electron-builder/src/targets/targetFactory.ts:57:12)
    at /home/kent/Documents/padlock/node_modules/electron-builder/src/packager.ts:224:28
From previous event:
    at Packager.doBuild (/home/kent/Documents/padlock/node_modules/electron-builder/out/packager.js:317:11)
    at /home/kent/Documents/padlock/node_modules/electron-builder/src/packager.ts:175:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
From previous event:
    at Packager.build (/home/kent/Documents/padlock/node_modules/electron-builder/out/packager.js:236:11)
    at Object.<anonymous> (/home/kent/Documents/padlock/node_modules/electron-builder/src/builder.ts:266:40)
    at Generator.next (<anonymous>)
From previous event:
    at Object.build (/home/kent/Documents/padlock/node_modules/electron-builder/out/builder.js:69:21)
    at rmdir.then.then.then.then.then (/home/kent/Documents/padlock/lib/build.js:170:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Building AppImage for arch x64

```

**Comment by MaKleSoft** [comment]
It's great that somebody is finally thoroughly kicking the tires on linux :) Haven't really had the chance to do that myself. Thanks for that!

Unfortunately, I'm unable to reproduce this on my mac. It looks like electron-builder can't find the `icon.icns` file under `resources/electron`. Can you try adding the following line to `lib/build.js`? 

```js
.then(() => builder.build({
    mac: options.mac && ["default"],
    win: options.win && ["nsis"],
    linux: options.linux && ["AppImage"],
    config: {
        appId: "com.maklesoft.padlock",
        publish: {
            provider: "github",
            owner: "maklesoft",
            repo: "padlock"
        },
        directories: {
            buildResources: "resources/electron",
            app: "dist/electron",
            output: "dist"
        },
        win: {
            publisherName: "Martin Kleinschrodt"
        },
        icon: "resources/electron/icon" // <= Insert this line
    },
    publish: options.release && "always"
}));
```

**Comment by KentShikama** [comment]
Fixed thanks to the hint at https://github.com/yishn/Sabaki/issues/241
