### ISSUE TITLE
Javascript error is thrown when opening app with npm run app on Ubuntu 16.04

### ISSUE THREAD

**Issue by KentShikama** [MaKleSoft/padlock#103]
```
npm run app

A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: Cannot read property 'then' of undefined
    at checkForUpdates (/home/kent/Documents/padlock/main.js:86:34)
    at App.app.on (/home/kent/Documents/padlock/main.js:220:5)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:194:7)
```

Note the app still works after closing the error so this is relatively non-critical.

**Comment by KentShikama** [comment]
@MaKleSoft Fixes the issue indeed. I've been using the beta release for a day now on Ubuntu and it is working as advertised. Thanks for this product :)

**Comment by MaKleSoft** [comment]
Thats great to hear. Thanks again for the feedback!
