### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by fvdb** [MaKleSoft/padlock#86]
Since today, when I start Padlock (on Mac OS), it fails with the following error in a popup:

```
A JavaScript error occurred in the main process

Uncaught Exception:
Error: Cannot find module 'electron-auto-updater'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Applications/Padlock.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Applications/Padlock.app/Contents/Resources/app.asar/main.js:4:23)
    at Object.<anonymous> (/Applications/Padlock.app/Contents/Resources/app.asar/main.js:109:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```

The app keeps running, but the main window doesn't show up. My version is 1.2.0-beta.2.

At this point the application is completely unusable. Please advise.

**Edit**
I updated to the alpha, and the same issue occurred. Perhaps Padlock auto updated to the alpha and the issue comes from there?

**Edit 2**
Overwriting padlock with a newly downloaded 1.2.0-beta.2 fixed the issue.

**Comment by MaKleSoft** [comment]
@fvdb Thanks for the detailed report! In fact it seems like it was a problem with the update process. We had published a new alpha version and apparently the app mistakenly downloaded the update (the auto updater should never switch from the beta to the alpha channel). We've since pulled the new release so simply redownloading the app should fix the issue as you've already noted.
